<a href="https://colab.research.google.com/github/Tverdostup1993/Python_for_ds_tasks/blob/main/%D0%A2%D0%B2%D0%B5%D1%80%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF_%D0%9E_%D0%86_%22HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8)_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [ ]:
import numpy as np
import random

In [ ]:
# Варіант 1: Вектор з random.uniform
vector1 = np.array([random.uniform(0, 1) for _ in range(10)])

# Варіант 2: Вектор з np.random.rand
vector2 = np.random.rand(10)

# Матриця 3x3
matrix = np.array([
    [11, 20, 29],
    [14, 23, 32],
    [17, 26, 35]
])

# Виведення результатів
print("Генерація випадкових чисел (random.uniform):")
print(vector1)
print("Розмір вектора:", vector1.shape)

print("\nВипадковий вектор (np.random.rand):")
print(vector2)
print("Розмір вектора:", vector2.shape)

print("\nМатриця:")
print(matrix)
print("Розмір матриці:", matrix.shape)

Генерація випадкових чисел (random.uniform):
[0.62660987 0.65399992 0.48074875 0.11517862 0.48064671 0.51297196
 0.09305426 0.31257162 0.46517501 0.37077122]
Розмір вектора: (10,)

Випадковий вектор (np.random.rand):
[0.08552803 0.53020779 0.90332796 0.85552203 0.65906721 0.80544006
 0.49432687 0.7397328  0.19126891 0.19944501]
Розмір вектора: (10,)

Матриця:
[[11 20 29]
 [14 23 32]
 [17 26 35]]
Розмір матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [ ]:
# Додаємо 10 і округлюємо до 2 знаків
vector1_plus_10 = np.round(vector1 + 10, 2)
vector2_plus_10 = np.round(vector2 + 10, 2)

print("Вектор1 + 10, округлений до 2 знаків:")
print(vector1_plus_10)
print("Вектор2 + 10, округлений до 2 знаків:")
print(vector2_plus_10)

Вектор1 + 10, округлений до 2 знаків:
[10.53 10.95 10.02 10.04 10.67 10.04 10.38 10.23 10.24 10.63]
Вектор2 + 10, округлений до 2 знаків:
[10.22 10.61 10.36 10.24 10.56 10.57 10.59 10.35 10.42 10.4 ]


In [ ]:
matrix_times_2 = matrix * 2

print("\nМатриця × 2:")
print(matrix_times_2)


Матриця × 2:
[[22 40 58]
 [28 46 64]
 [34 52 70]]


In [ ]:
vector1_squared = np.square(vector1)
vector2_squared = np.square(vector2)

print("\nКвадрат значень вектора:")
print(vector1_squared)

print("\nКвадрат значень вектора:")
print(vector2_squared)


Квадрат значень вектора:
[2.76197873e-01 9.11311361e-01 3.67064914e-04 1.40497118e-03
 4.43479814e-01 1.74873281e-03 1.40739606e-01 5.40922593e-02
 5.88475633e-02 3.99479241e-01]

Квадрат значень вектора:
[0.0503328  0.36837976 0.13044409 0.05823614 0.30914404 0.32219926
 0.34639515 0.12555114 0.17536542 0.16385379]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [ ]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [ ]:
result_matrix = np.dot(B, A)

print(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]


In [ ]:
result_matrix_C=result_matrix * C
print(result_matrix_C)

[[0.     0.    ]
 [0.2034 0.2846]]


In [ ]:
result_matrix_D=result_matrix * D
print(result_matrix_D)

[[0.     0.5202]
 [0.2034 0.    ]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [ ]:
result_matrix_T = result_matrix.T
print(result_matrix_T)

[[0.7281 0.2034]
 [0.5202 0.2846]]


In [ ]:
vector_T = vector2.T
print (vector_T)

[0.08552803 0.53020779 0.90332796 0.85552203 0.65906721 0.80544006
 0.49432687 0.7397328  0.19126891 0.19944501]


Немає різниці через те що ми транспортуємо одномірний вектор

In [ ]:
vector2_expand = np.expand_dims(vector2, axis=1)
print (vector2_expand)

[[0.08552803]
 [0.53020779]
 [0.90332796]
 [0.85552203]
 [0.65906721]
 [0.80544006]
 [0.49432687]
 [0.7397328 ]
 [0.19126891]
 [0.19944501]]


Перетворили вектор на стовпчик (10×1). Тепер це матриця з однією колонкою.

In [ ]:
vector2_expand_T = vector2_expand.T
print (vector2_expand_T)
print("Розмір матриці:", vector2_expand_T.shape)

[[0.08552803 0.53020779 0.90332796 0.85552203 0.65906721 0.80544006
  0.49432687 0.7397328  0.19126891 0.19944501]]
Розмір матриці: (1, 10)
